services:
  frontend:
    build: .
    ports:
      - "5173:5173"
    depends_on:
      - backend


  backend:
    build:
      context: ../cookflow-backend
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_NAME: cookflow_db
      DB_USER: admin
      DB_PASSWORD: admin
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: cookflow_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
        - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 