services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: cookflow_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - cookflow_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d cookflow_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ../CF-Backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      DJANGO_ALLOWED_HOSTS: "frontend,backend,localhost,127.0.0.1,host.docker.internal"
      DJANGO_CORS_ALLOWED_ORIGINS: "http://frontend:80,http://localhost:5173,http://127.0.0.1:5173,http://localhost:80,http://127.0.0.1:80,http://host.docker.internal:80"
      DATABASE_URL: postgres://admin:admin@db:5432/cookflow_db
      HEALTHCHECK_URL: http://localhost:8000/admin/
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/admin/"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 30s

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 10s
      timeout: 5s
      retries: 10
    environment:
      VITE_API_URL: http://backend:8000/api
      VITE_HMR_HOST: frontend
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      backend:
        condition: service_healthy

  cypress:
    # --- IMPORTANT CHANGE START ---
    # Removed 'build' and 'dockerfile' as we are using a pre-built Cypress image.
    image: cypress/included:13.13.1 # Using a Cypress image that includes all necessary browser dependencies
    # --- IMPORTANT CHANGE END ---
    environment:
      CYPRESS_BASE_URL: http://frontend:80
      CYPRESS_API_URL: http://backend:8000/api
      # DISPLAY: 172.30.48.1:0.0
    volumes:
      # Ensure your local Cypress test files and config are mapped into the container
      - ./cypress:/e2e/cypress # Maps your cypress folder containing tests
      - ./cypress.config.js:/e2e/cypress.config.js
      - ./package.json:/e2e/package.json
      - ./package-lock.json:/e2e/package-lock.json
      - /e2e/node_modules
    working_dir: /e2e
    depends_on:
      frontend:
        condition: service_healthy
      backend:
        condition: service_healthy
    ports:
      - "8080:8080"

volumes:
  cookflow_db_data: