import AddRecipe from "./AddRecipe";
import AdminDashboard from "./AdminDashboard";
import Home from "./Home";
import InspireMe from "./InspireMe";
import Login from "./Login";
import Profile from "./Profile";
import Recipe from "./Recipe";
import Search from "./Search";
import SignIn from "./SignIn";