name: Frontend CI & E2E Tests

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]
  repository_dispatch:
    types: [backend_update]

jobs:
  build-and-push-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Frontend Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            hemaps/cookflow-frontend:latest
            hemaps/cookflow-frontend:${{ github.sha }}

  e2e-tests:
    runs-on: ubuntu-latest
    needs: build-and-push-frontend
    if: |
      github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev') ||
      github.event_name == 'repository_dispatch' && github.event.action == 'backend_update'
    steps:
      - name: Checkout Frontend Code (incl. docker-compose.yml and cypress)
        uses: actions/checkout@v4

      - name: Login to Docker Registry (needed to pull backend image)
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Cypress & Start All Services
        run: docker compose up -d --build

      # Custom Wait for DB (replaces 'docker compose wait db')
      - name: Custom Wait for DB to be healthy (using pg_isready)
        run: |
          echo "Starting custom wait for DB..."
          MAX_RETRIES=60 # Roughly 5 minutes (60 retries * 5 seconds sleep)
          RETRY_COUNT=0
          while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
            echo "Attempt $((RETRY_COUNT + 1)) of $MAX_RETRIES: Checking DB readiness..."
            # The -T flag is important to prevent pseudo-TTY allocation issues in CI.
            if docker compose exec -T db sh -c "pg_isready -h localhost -p 5432 -U postgres"; then
              echo "DB is ready! Proceeding."
              exit 0
            fi
            RETRY_COUNT=$((RETRY_COUNT + 1))
            sleep 5 # Wait for 5 seconds before retrying
          done
          echo "Error: DB did not become healthy within the timeout period."
          exit 1

      - name: Wait for Backend to be healthy
        run: docker compose wait backend

      # --- START: Debug Backend Healthcheck Status (New Debugging Step) ---
      - name: Debug Backend Healthcheck Status
        if: always() # Run this even if previous steps fail
        run: |
          echo "--- Current Docker Compose Services Status ---"
          docker compose ps -a
          echo "--- Inspecting Backend Container Health ---"
          docker inspect --format='{{json .State.Health}}' cf-frontend-backend-1 || echo "Could not inspect backend health."
          echo "--- Full Backend Container Logs (from Docker) ---"
          docker logs cf-frontend-backend-1 || echo "Could not retrieve backend logs."
        continue-on-error: true # Allow the workflow to finish, don't stop here
      # --- END: Debug Backend Healthcheck Status ---

      - name: Wait for Frontend to be healthy
        run: docker compose wait frontend

      - name: Run Backend Migrations & Seed Data
        run: docker compose run --rm backend sh -c "python manage.py migrate --noinput && python manage.py seed_all"

      - name: Run Cypress E2E Tests (Headless)
        run: docker compose run --rm --entrypoint "" cypress sh -c "cd /e2e && npx cypress run --project ./"
        env:
          CYPRESS_BASE_URL: http://frontend:80
          CYPRESS_API_URL: http://backend:8000/api

      - name: Clean up Docker Compose
        if: always()
        run: docker compose down