name: Frontend CI & E2E Tests

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]
  repository_dispatch:
    types: [backend_update]

jobs:
  build-and-push-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Frontend Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            hemaps/cf-frontend:latest
            hemaps/cf-frontend:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  e2e-tests:
    runs-on: ubuntu-latest
    needs: build-and-push-frontend
    if: |
      github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev') ||
      github.event_name == 'repository_dispatch' && github.event.action == 'backend_update'
    steps:
      - name: Create common workspace directory
        run: mkdir common-workspace

      - name: Checkout Frontend Code
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          path: common-workspace/CF-Frontend

      - name: Checkout Backend Code
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/CF-Backend
          path: common-workspace/CF-Backend

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set Project Name
        run: echo "COMPOSE_PROJECT_NAME=cf" >> $GITHUB_ENV
        working-directory: common-workspace/CF-Frontend

      - name: Verify Compose Config
        run: docker compose config
        working-directory: common-workspace/CF-Frontend

      # --- CRITICAL CHANGE: Build and Start ALL services early ---
      - name: Build and Start All Services
        run: docker compose up -d --build
        working-directory: common-workspace/CF-Frontend

      - name: Wait for DB to be healthy
        timeout-minutes: 5
        run: |
          echo "Starting custom wait for DB..."
          MAX_RETRIES=60
          RETRY_COUNT=0
          while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
            echo "Attempt $((RETRY_COUNT + 1)) of $MAX_RETRIES: Checking DB readiness..."
            if docker compose exec -T db sh -c "pg_isready -h localhost -p 5432 -U admin -d cookflow_db"; then
              echo "DB is ready! Proceeding."
              exit 0
            fi
            RETRY_COUNT=$((RETRY_COUNT + 1))
            sleep 5
            echo "DB not ready yet... Retrying in 5s."
          done
          echo "Error: DB did not become healthy within the timeout period."
          exit 1
        working-directory: common-workspace/CF-Frontend

      - name: Wait for Backend to be healthy
        timeout-minutes: 5
        run: |
          echo "Waiting for backend to be healthy..."
          MAX_RETRIES=30
          RETRY_COUNT=0
          until docker compose exec -T backend curl -f http://localhost:8000/admin/; do # Added -f for fail silently
            RETRY_COUNT=$((RETRY_COUNT + 1))
            if [ $RETRY_COUNT -ge $MAX_RETRIES ]; then
              echo "Error: Backend did not become healthy within the timeout period."
              docker compose logs backend
              exit 1
            fi
            sleep 10
            echo "Backend not ready yet... Retrying in 10s."
            docker compose logs backend
          done
          echo "Backend is healthy!"
        working-directory: common-workspace/CF-Frontend

      - name: Wait for Frontend to be healthy
        timeout-minutes: 5
        run: |
          echo "Waiting for frontend to be healthy..."
          MAX_RETRIES=30
          RETRY_COUNT=0
          until curl -sf http://localhost:5173 >/dev/null; do
            RETRY_COUNT=$((RETRY_COUNT + 1))
            if [ $RETRY_COUNT -ge $MAX_RETRIES ]; then
              echo "Error: Frontend did not become healthy within the timeout period."
              docker compose logs frontend
              exit 1
            fi
            sleep 10
            echo "Frontend not ready yet... Retrying in 10s."
            docker compose logs frontend
          done
          echo "Frontend is healthy!"
        working-directory: common-workspace/CF-Frontend

      # --- Now that all services are built and running, execute commands on them ---
      - name: Verify Backend Python Environment
        run: docker compose exec backend sh -c "which python && python --version && pip list"
        working-directory: common-workspace/CF-Frontend

      - name: Run Backend Migrations
        run: docker compose exec backend python manage.py migrate --noinput
        working-directory: common-workspace/CF-Frontend

      - name: Seed Database
        run: docker compose exec backend python manage.py seed_all
        working-directory: common-workspace/CF-Frontend

      - name: Run Cypress E2E Tests (Headless)
        timeout-minutes: 10
        run: docker compose run --rm --entrypoint "" cypress sh -c "cd /e2e && npx cypress run --project ./"
        env:
          CYPRESS_BASE_URL: http://frontend:80
          CYPRESS_API_URL: http://backend:8000/api
        working-directory: common-workspace/CF-Frontend

      - name: Upload Cypress Screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
            name: cypress-screenshots
            path: common-workspace/CF-Frontend/cypress/screenshots

      - name: Upload Cypress Videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
            name: cypress-videos
            path: common-workspace/CF-Frontend/cypress/videos

      - name: Clean up Docker Compose
        if: always()
        run: docker compose down -v --remove-orphans
        working-directory: common-workspace/CF-Frontend

# The Backend CI & E2E Trigger workflow (in CF-Backend repo) remains unchanged.